# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanmodel',
            name='location',
            field=models.TextField(default='p', max_length=500),
            preserve_default=False,
        ),
    ]
