# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_results_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='question',
        ),
        migrations.DeleteModel(
            name='Results',
        ),
    ]
